<?php

$config = array(
		// The MySQL host to connect to
		'host' => "localhost",
		// The MySQL database to connect to
		'dbname' => "bzgrpmgr",
		// The MySQL username to use
		'user' => "bzgrpmgr",
		// The MySQL password to use
		'pass' => "bzgrpmgr",
		// The table prefix for the site to use
		'prefix' => "groups_",
		// The table name of the phpBB users table
		'users_table' => "phpbb2_users"
	);
?>
