<!-- End <?=$PHP_SELF?>, begin footer.inc -->

<p class="refreshed">Database last refreshed: <?=$refreshed_date?></p>

<div id="footercontainer">

<div id="copyright">
<a href="copyright.php">
copyright &copy;</a> 2003 <a href="http://www.noodleroni.com/contact.php">Tucker McLean</a>
</div>

<div id="footer">
view source: <a href="<?=$PHP_SELF?>?viewsource=1">this page</a> | <a href="<?=$PHP_SELF?>?viewsource=header">header</a> | <a href="<?=$PHP_SELF?>?viewsource=footer">footer</a> | <a href="<?=$PHP_SELF?>?viewsource=rss">rss feed</a>
</div>

</div>

</div>

</div>

</body>
</html>
