//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BZEdit32.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BZWLDTYPE                   129
#define IDI_BOXWALL_ICON                130
#define IDI_LINK_ICON                   131
#define IDI_BASE_ICON                   132
#define IDI_TPORT_ICON                  133
#define IDI_PYRAMID_ICON                134
#define IDD_ELEMENT_LIST_DLOG           135
#define IDB_LIST_IMAGES                 136
#define IDD_ELEMENT_INSP                137
#define IDB_SPLASH                      139
#define IDR_NEWENT_BAR                  140
#define IDD_STD_INFO_DLOG               142
#define IDD_LINK_INTERFACE              143
#define IDD_DUPE_AND                    146
#define IDC_ELEMENT_FILTER              1000
#define IDC_ELEMENT_LIST_CTL            1002
#define IDC_REMOVE_ITEM                 1003
#define IDC_ITEM_NAME_EDIT              1004
#define IDC_ITEM_TYPE_EDIT              1005
#define IDC_POS_X_EDIT                  1006
#define IDC_POS_Y_EDIT                  1007
#define IDC_DUPLICATE                   1008
#define IDC_POS_Z_EDIT                  1009
#define IDC_OPTIONAL_FRAME              1010
#define IDC_OTHER_LAB1                  1011
#define IDC_OTHER_LAB2                  1012
#define IDC_ROT_Z_EDIT                  1013
#define IDC_POS_X_LAB                   1014
#define IDC_POS_Y_LAB                   1015
#define IDC_SCALE_X_EDIT                1016
#define IDC_SCALE_Y_EDIT                1017
#define IDC_SCALE_Z_EDIT                1018
#define IDC_OTHER_EDIT_1                1019
#define IDC_OTHER_EDIT2                 1020
#define IDC_POS_Z_LAB                   1021
#define IDC_POS_FRAME                   1022
#define IDC_ROT_FRAME                   1023
#define IDC_ROT_Z_LAB                   1024
#define IDC_SCALE_FRAME                 1025
#define IDC_SCALE_X_LAB                 1026
#define IDC_SCALE_Y_LAB                 1027
#define IDC_SCALE_Z_LAB                 1028
#define IDC_APPLY                       1029
#define IDC_GROUPS_LABEL                1032
#define IDC_GROUP_LIST                  1033
#define IDC_ADD_SEL_TO_GROUP            1034
#define IDC_SELECT_GROUP                1036
#define IDC_HIDE_GROUP                  1037
#define IDC_NEW_GROUP                   1038
#define IDC_ADD                         1039
#define IDC_CHILD_DLOG_FRAME            1040
#define IDC_XPOS                        1041
#define IDC_YPOS                        1042
#define IDC_ZPOS                        1043
#define IDC_XSCALE                      1044
#define IDC_YSCALE                      1045
#define IDC_ZSCALE                      1046
#define IDC_ZROT                        1047
#define IDC_BORDER                      1048
#define IDC_BORDER_LABEL                1050
#define IDC_TO_TP                       1055
#define IDC_TEAM_LIST                   1055
#define IDC_TO_SIDE                     1056
#define IDC_TEAM_LABEL                  1056
#define IDC_FROM_TP                     1057
#define IDC_FROM_SIDE                   1058
#define IDC_NUM_DUPES                   1059
#define IDC_TRANSLATE                   1060
#define IDC_X_TRANS_LABEL               1061
#define IDC_X_TRANS_TE                  1062
#define IDC_Y_TRANS_LABEL               1063
#define IDC_Y_TRANS_TE                  1064
#define IDC_Z_TRANS_LABEL               1065
#define IDC_Z_TRANS_TE                  1066
#define IDC_SCALE                       1067
#define IDC_X_SCALE_LABEL               1068
#define IDC_X_SCALE_TE                  1069
#define IDC_Y_SCALE_LABEL               1070
#define IDC_Y_SCALE_TE                  1071
#define IDC_Z_SCALE_LABEL               1072
#define IDC_Z_SCALE_TE                  1073
#define IDC_TRANS_FRAME                 1074
#define IDC_ROTATE                      1075
#define IDC_TRANS_W_ROT                 1076
#define IDC_DRIVE_THRU                  1077
#define IDC_SHOOT_THRU                  1078
#define IDC_FLIPZ                       1079
#define IDC_Z_ROT_LABEL                 1080
#define IDC_Z_ROT_TE                    1081
#define ID_VIEW_GRID                    32771
#define ID_VIEW_ELEMENTLIST             32772
#define ID_Z_PLUS_VIEW                  32773
#define ID_Y_MINUS_VIEW                 32774
#define ID_X_MINUS_VIEW                 32775
#define ID_Y_PLUS_VIEW                  32776
#define ID_X_PLUS_VIEW                  32777
#define ID_ISO_VIEW                     32779
#define ID_CENTER_VIEW                  32781
#define ID_ADD_BOX                      32782
#define ID_ADD_PYRAMID                  32783
#define ID_ADD_TPORT                    32784
#define ID_ADD_LINK                     32785
#define ID_ADD_BASE                     32786
#define ID_VIEW_ELEMENTINSPECTOR        32788
#define ID_UTILTY_CONVERTMAPFILETODEG   32789
#define ID_UTILTY_CONVERTMAPFILETORAD   32790
#define ID_EDIT_MAKEANGLESDEG           32791
#define ID_EDIT_MAKEANGLESROT           32792
#define ID_VIEW_MOVETOSELECTION         32793
#define ID_UTILTY_DUPLICATE             32794
#define ID_UTILTY_DUPLICATEAND          32795
#define ID_ADD_CUSTOM                   32796
#define ID_ZOOM_TO_SELECTION            32797
#define ID_MAKE_TRANS_ON_SLECT          32798
#define ID_SELECT_MODE                  32799
#define ID_HV_MOVE                      32800
#define ID_HD_PAN                       32801
#define ID_ROTOATE                      32802
#define ID_SCALE                        32804
#define ID_BUTTON32805                  32805
#define ID_BUTTON32806                  32806
#define ID_UTILTY_DUMPMAP               32807
#define ID_BOX_BUTON                    32809
#define ID_SHOW_ALL                     32811
#define ID_PYR_BUTON                    32812
#define ID_TP_BUTTON                    32813
#define ID_LINK_BUTTON                  32814
#define ID_BASE_BUTTON                  32815
#define ID_UTILTY_DUPEANDFLIPX          32816
#define ID_UTILTY_DUPEANDFLIPY          32817
#define ID_PLUGINS_DUMMY                32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

